version: '3.8'

services:
  youtube-downloader-bot:
    build: .
    container_name: youtube_downloader_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
